version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nova_senha
      POSTGRES_DB: checklist_residencial
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://postgres:nova_senha@localhost:5434/checklist_residencial?schema=public"
    volumes:
      - .:/usr/src/app
    command: bash -c "npx prisma migrate deploy && npm run dev"

volumes:
  postgres-data: